name: Delete Wrong Logo

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete file
        run: |
          git rm "cybertalenthire-logo.png.png"
          git commit -m "Remove duplicate logo"
          git push
